name: InLine
author: danielec81
category: Forms
tags: [inline, form, interface]
demo: https://sites.google.com/site/jsplugin/projects/inline/demo---inline
docs: https://sites.google.com/site/jsplugin/projects/inline
current: 1.0b